<?php
$baseUrl = 'http://example.com/extensions/xml/';
$extensions = array(
  1 => array(
    'title'       => 'SAX',
    'description' => 'ext/xml provides a SAX XML parser generator',
    'link'        => $baseUrl . 'sax'
  ),
  2 => array(
    'title'       => 'DOM',
    'description' => 'The DOM extension provides an implementation of DOM, the Document Object Model',
    'link'        => $baseUrl . 'dom'
  ),
  3 => array(
    'title'       => 'XPath',
    'description' => 'XPath is used to query XML documents for elements',
    'link'        => $baseUrl . 'xpath'
  ),
  4 => array(
    'title'       => 'XSL',
    'description' => 'The XSL extension provides the ability to apply eXtensible Stylesheet Transformations (XSLT) on DOM documents',
    'link'        => $baseUrl . 'xsl'
  ),
  5 => array(
    'title'       => 'SimpleXML',
    'description' => 'SimpleXML provides OOP access to XML documents',
    'link'        => $baseUrl . 'simplexml'
  ),
  6 => array(
    'title'       => 'XMLReader',
    'description' => 'XMLReader provides an XML Pull implementation for PHP',
    'link'        => $baseUrl . 'xmlreader'
  ),
  7 => array(
    'title'       => 'XMLWriter',
    'description' => 'XMLWriter provides functions and OOP methods for generating XML documents',
    'link'        => $baseUrl . 'xmlwriter'
  ),
  8 => array(
    'title'       => 'XML-RPC',
    'description' => 'XML-RPC extension for creating PHP XML-RPC client and server implementations',
    'link'        => $baseUrl . 'xmlrpc'
  ),
  9 => array(
    'title'       => 'SOAP',
    'description' => 'SOAP protocol layer for PHP, including a client and server implementation',
    'link'        => $baseUrl . 'soap'
  )
);
?>